name: Java Unit Test CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: 'true'
  JAVA_VERSION: '17'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código fonte
        uses: actions/checkout@v5

      - name: Configurar o ambiente Java
        uses: actions/setup-java@v5
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'

      - name: Compilar e Executar Testes Unitários
        run: ant test